components_manager:
    task_processors:
        main-task-processor:
            worker_threads: $worker-threads

        fs-task-processor:
            worker_threads: $worker-fs-threads

    default_task_processor: main-task-processor

    components:
        server:
            listener:
                port: $server-port
                task_processor: main-task-processor

        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: $log-file-path
                    format: $logger-format
                    level: $logger-level
                    overflow_behavior: discard

        dynamic-config:
            defaults:
                HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000
                POSTGRES_DEFAULT_COMMAND_CONTROL:
                    network_timeout_ms: 750
                    statement_timeout_ms: 500

        testsuite-support: {}

        congestion-control:

        http-client:
        http-client-core:
            load-enabled: $is_testing
            fs-task-processor: fs-task-processor

        dns-client:
            fs-task-processor: fs-task-processor

        tidy_pg:
            dbconnection: $pg-connection
            dbconnection#env: DB_CONNECTION
            blocking_task_processor: fs-task-processor
            dns_resolver: async
            sync-start: true
            connlimit_mode: manual

        user-tokens-pg-cache:
            pgcomponent: tidy_pg
            update-types: full-and-incremental
            update-interval: 15s
            full-update-interval: 6h

        tests-control:
            load-enabled: $is-testing
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor

        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        # admin endpoints
        handler-admin_v1_users-get:
            path: /admin/v1/users
            method: GET
            task_processor: main-task-processor
            auth:
                types:
                  - cookie-required
                scopes:
                  - admin

        handler-admin_v1_users_delete-post:
            path: /admin/v1/users/delete
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - cookie-required
                scopes:
                  - admin

        handler-admin_v1_users_user_role-post:
            path: /admin/v1/users/{user}/role
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - cookie-required
                scopes:
                  - admin

        handler-admin_v1_queues-get:
            path: /admin/v1/queues
            method: GET
            task_processor: main-task-processor
            auth:
                types:
                  - cookie-required
                scopes:
                  - admin

        handler-admin_v1_queues_delete-post:
            path: /admin/v1/queues/delete
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - cookie-required
                scopes:
                  - admin

        handler-admin_v1_issues-get:
            path: /admin/v1/issues
            method: GET
            task_processor: main-task-processor
            auth:
                types:
                  - cookie-required
                scopes:
                  - admin

        handler-admin_v1_issues_delete-post:
            path: /admin/v1/issues/delete
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - cookie-required
                scopes:
                  - admin

        # user endpoints
        handler-v1_users_me-get:
            path: /v1/users/me
            method: GET
            task_processor: main-task-processor
            auth:
                types:
                  - cookie-required

        handler-v1_users_me-put:
            path: /v1/users/me
            method: PUT
            task_processor: main-task-processor
            auth:
                types:
                  - cookie-required

        handler-v1_users_me_delete-post:
            path: /v1/users/me/delete
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - cookie-required

        handler-v1_users_me_password-put:
            path: /v1/users/me/password
            method: PUT
            task_processor: main-task-processor
            auth:
                types:
                  - cookie-required

        # auth endpoints
        handler-v1_auth_login-post:
            path: /v1/auth/login
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - cookie-optional

        handler-v1_auth_register-post:
            path: /v1/auth/register
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - cookie-optional

        handler-v1_auth_logout-post:
            path: /v1/auth/logout
            method: POST
            task_processor: main-task-processor

        # queues endpoints
        handler-v1_queues-get:
            path: /v1/queues
            method: GET
            task_processor: main-task-processor
            auth:
                types:
                  - cookie-required

        handler-v1_queues-post:
            path: /v1/queues
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - cookie-required

        handler-v1_queues_queue_delete-post:
            path: /v1/queues/{queue}/delete
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - cookie-required

        handler-v1_queues_queue_permissions-post:
            path: /v1/queues/{queue}/permissions
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - cookie-required

        handler-v1_queues_queue_permissions_delete-post:
            path: /v1/queues/{queue}/permissions/delete
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - cookie-required

        handler-v1_queues_queue_issues-post:
            path: /v1/queues/{queue}/issues
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - cookie-required

        handler-v1_queues_queue_issues-get:
            path: /v1/queues/{queue}/issues
            method: GET
            task_processor: main-task-processor
            auth:
                types:
                  - cookie-required

        handler-v1_queues_queue_issues_issue-get:
            path: /v1/queues/{queue}/issues/{issue}
            method: GET
            task_processor: main-task-processor
            auth:
                types:
                  - cookie-required

        handler-v1_queues_queue_issues_issue_delete-post:
            path: /v1/queues/{queue}/issues/{issue}/delete
            method: POST
            task_processor: main-task-processor
            auth:
                types:
                  - cookie-required

        handler-v1_queues_queue_issues_issue-put:
            path: /v1/queues/{queue}/issues/{issue}
            method: PUT
            task_processor: main-task-processor
            auth:
                types:
                  - cookie-required
