openapi: 3.0.0

info:
    title: Tidy Service
    version: '1.0'

servers:
  - url: https://api.tidyapp.uz
    description: production
  - url: http://127.0.0.1:8080
    description: testing

paths:
    /admin/v1/users:
        get:
            tags:
              - admin
            parameters:
              - $ref: common.yaml#/components/parameters/SessionIdCookieRequired
              - $ref: common.yaml#/components/parameters/SearchQuery
              - $ref: common.yaml#/components/parameters/PageQuery
              - $ref: common.yaml#/components/parameters/LimitQuery
            responses:
                200:
                    description: list of users
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AdminV1UsersResponse'
                400:
                    description: invalid query params
                    content:
                        application/json:
                            schema:
                                $ref: errors.yaml#/components/schemas/ErrorResponse

    /admin/v1/users/delete:
        post:
            tags:
              - admin
            parameters:
              - $ref: common.yaml#/components/parameters/SessionIdCookieRequired
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AdminV1UsersDeleteRequest'
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AdminV1UsersDeleteResponse'

    /admin/v1/users/{user}/role:
        post:
            tags:
              - admin
            parameters:
              - $ref: common.yaml#/components/parameters/SessionIdCookieRequired
              - $ref: common.yaml#/components/parameters/UserArg
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AdminV1UsersUserRoleRequest'
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AdminV1UsersUserRoleResponse'
                404:
                    description: user not found
                    content:
                        application/json:
                            schema:
                                $ref: errors.yaml#/components/schemas/ErrorResponse

    /admin/v1/queues:
        get:
            tags:
              - admin
            parameters:
              - $ref: common.yaml#/components/parameters/SessionIdCookieRequired
              - $ref: common.yaml#/components/parameters/SearchQuery
              - $ref: common.yaml#/components/parameters/PageQuery
              - $ref: common.yaml#/components/parameters/LimitQuery
            responses:
                200:
                    description: list of queues
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AdminV1QueuesResponse'
                400:
                    description: invalid query params
                    content:
                        application/json:
                            schema:
                                $ref: errors.yaml#/components/schemas/ErrorResponse

    /admin/v1/queues/delete:
        post:
            tags:
              - admin
            parameters:
              - $ref: common.yaml#/components/parameters/SessionIdCookieRequired
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AdminV1QueuesDeleteRequest'
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AdminV1QueuesDeleteResponse'

    /admin/v1/issues:
        get:
            tags:
              - admin
            parameters:
              - $ref: common.yaml#/components/parameters/SessionIdCookieRequired
              - $ref: common.yaml#/components/parameters/SearchQuery
              - $ref: common.yaml#/components/parameters/PageQuery
              - $ref: common.yaml#/components/parameters/LimitQuery
            responses:
                200:
                    description: list of issues
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AdminV1IssuesResponse'
                400:
                    description: invalid query params
                    content:
                        application/json:
                            schema:
                                $ref: errors.yaml#/components/schemas/ErrorResponse

    /admin/v1/issues/delete:
        post:
            tags:
              - admin
            parameters:
              - $ref: common.yaml#/components/parameters/SessionIdCookieRequired
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AdminV1IssuesDeleteRequest'
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AdminV1IssuesDeleteResponse'

components:
    schemas:
        AdminV1UsersRequest:
            type: object
            additionalProperties: false

        AdminV1UsersResponse:
            type: object
            additionalProperties: false
            required:
              - users
            properties:
                users:
                    type: array
                    items:
                        $ref: '#/components/schemas/AdminUserListItem'

        AdminUserListItem:
            type: object
            additionalProperties: false
            required:
              - id
              - email
              - username
              - role
              - removed
              - created_at
              - updated_at
            properties:
                id:
                    type: string
                    format: uuid
                full_name:
                    type: string
                email:
                    type: string
                username:
                    type: string
                role:
                    $ref: users.yaml#/components/schemas/UserRole
                removed:
                    type: boolean
                created_at:
                    type: integer
                    format: int64
                updated_at:
                    type: integer
                    format: int64

        AdminV1UsersDeleteRequest:
            type: object
            additionalProperties: false
            required:
              - user_ids
            properties:
                user_ids:
                    type: array
                    items:
                        type: string
                        format: uuid
                    x-usrv-cpp-type: std::unordered_set

        AdminV1UsersDeleteResponse:
            type: object
            additionalProperties: false

        AdminV1UsersUserRoleRequest:
            type: object
            additionalProperties: false
            required:
              - role
            properties:
                role:
                    $ref: users.yaml#/components/schemas/UserRole

        AdminV1UsersUserRoleResponse:
            type: object
            additionalProperties: false

        AdminV1QueuesRequest:
            type: object
            additionalProperties: false

        AdminV1QueuesResponse:
            type: object
            additionalProperties: false
            required:
              - queues
            properties:
                queues:
                    type: array
                    items:
                        $ref: '#/components/schemas/AdminQueueListItem'

        AdminQueueListItem:
            type: object
            additionalProperties: false
            required:
              - id
              - key
              - name
              - owner
              - removed
              - created_at
              - updated_at
            properties:
                id:
                    type: string
                    format: uuid
                key:
                    type: string
                name:
                    type: string
                owner:
                    $ref: users.yaml#/components/schemas/UserRef
                removed:
                    type: boolean
                created_at:
                    type: integer
                    format: int64
                updated_at:
                    type: integer
                    format: int64

        AdminV1QueuesDeleteRequest:
            type: object
            additionalProperties: false
            required:
              - queue_ids
            properties:
                queue_ids:
                    type: array
                    items:
                        type: string
                        format: uuid
                    x-usrv-cpp-type: std::unordered_set

        AdminV1QueuesDeleteResponse:
            type: object
            additionalProperties: false

        AdminV1IssuesRequest:
            type: object
            additionalProperties: false

        AdminV1IssuesResponse:
            type: object
            additionalProperties: false
            required:
              - issues
            properties:
                issues:
                    type: array
                    items:
                        $ref: '#/components/schemas/AdminIssueListItem'

        AdminIssueListItem:
            type: object
            additionalProperties: false
            required:
              - id
              - queue
              - number
              - title
              - type
              - status
              - priority
              - removed
            properties:
                id:
                    type: string
                    format: uuid
                queue:
                    type: object
                    additionalProperties: false
                    required:
                      - id
                      - key
                    properties:
                        id:
                            type: string
                            format: uuid
                        key:
                            type: string
                number:
                    type: integer
                title:
                    type: string
                description:
                    type: string
                type:
                    $ref: issues.yaml#/components/schemas/IssueType
                status:
                    $ref: issues.yaml#/components/schemas/IssueStatus
                priority:
                    $ref: issues.yaml#/components/schemas/IssuePriority
                component:
                    type: string
                story_points:
                    type: integer
                removed:
                    type: boolean
                author:
                    $ref: users.yaml#/components/schemas/UserRef
                assignee:
                    $ref: users.yaml#/components/schemas/UserRef
                created_at:
                    type: integer
                    format: int64
                updated_at:
                    type: integer
                    format: int64

        AdminV1IssuesDeleteRequest:
            type: object
            additionalProperties: false
            required:
              - issue_ids
            properties:
                issue_ids:
                    type: array
                    items:
                        type: string
                        format: uuid
                    x-usrv-cpp-type: std::unordered_set

        AdminV1IssuesDeleteResponse:
            type: object
            additionalProperties: false
