[SERVICE]
    flush         1
    daemon        off
    log_level     info
    parsers_file  parsers.conf
    plugins_file  plugins.conf

[INPUT]
    Name                tail
    Path                /var/log/tidy-api/server.log
    Tag                 tidy-api
    DB                  /opt/fluent-bit/tidy-api.db
    DB.sync             normal
    Refresh_Interval    10
    Rotate_Wait         30
    Skip_Long_Lines     Off
    Mem_Buf_Limit       50MB
    Parser              json

[OUTPUT]
    Name            yc-logging
    Match           *
    group_id        <group_id>
    folder_id       <folder_id>
    message_key     text
    level_key       level
    default_level   info
    authorization   iam-key-file:/etc/tidy-api/iam_key.json
